### ISSUE TITLE
Manage oxAuth Key Rotation for HSM

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/replication-mgr#4]
For OpenID Connect, we want to rotate keys every two days. If we are managing keys in an HSM, it would be convenient if Replication Manager did this task. The right interface for this would be PKCS 11, because the HSM may be SoftHSM or some other HSM.

**Comment by iromli** [comment]
@qbert2k can we reuse KeyGenerator class for other HSM?

**Comment by nynymike** [comment]
I don't think so. The HSM has key operations. I think we'll have to send the right REST commands to instruct the HSM to generate new keys.

**Comment by iromli** [comment]
Done at e92b2719c16eab97174b750d3b19070d0fac37e4.
